### ISSUE TITLE
spi protocoll

### ISSUE THREAD

**Issue by 7be** [7be/App4UCU#15]
a protocoll is defined which controlls the data send and received by the ucu | the protocoll is presented to the group
-- | --

**Comment by JippieBrown** [comment]
In the Link below you find a rough overview about SPI protocol. Additionally can be thought about checksum or crc. During the second next spirnt i can test the arduino example.

https://docs.google.com/document/d/1puh_cC26BwSg677bHTc8bLs46kAenGwyTTajYXKuw1U/edit#heading=h.sinmt2mw84tn
